### ISSUE TITLE
[Enhancement] Workflow to Check `todo` Tag on Issue/PR

### ISSUE THREAD

**Issue by vaguecoder** [vaguecoder/gorilla-mux#35]
## Is your enhancement request related to a problem on existing feature? Please describe.
Naah!

## Describe the solution you'd like
At this point, it is just an idea. Need to check if a GitHub action workflow can detect the `todo` tag and fail the workflow for the developer to manually check and finish the TODOs. 

## Describe alternatives you've considered
If automation on this doesn't work (or too much of hard work for this simple thing), we have to stick to manually checking before approving the PRs (for `todo` tags on both PR & issue).

## Additional context
- `todo` tags on open issues/PRs can be found [here][1].
- Initial thought of adding `todo` is to signify that the issue or PR has some action items which have to be converted as issues. But this can be open-ended in future.

## TODO (if any)
Add details of what `todo` tag does, as explained above, in `CONTRIBUTING.md`

## Ownership of Contribution
If the triage is approved,
- [ ] I wish to submit the PR myself.
- [x] I wish to submit the PR. But if someone is willing to do it, go ahead.
- [ ] I don't know how to fix this or make these changes. I wish others to pick this up for me.

[1]: https://github.com/vaguecoder/gorilla-mux/labels/todo
