### ISSUE TITLE
[Enhancement] Add `TODO` Section in All Issue Templates

### ISSUE THREAD

**Issue by vaguecoder** [vaguecoder/gorilla-mux#36]
## Is your enhancement request related to a problem on existing feature? Please describe.
NA

## Describe the solution you'd like
Add `TODO` Section in All Issue Templates

## Describe alternatives you've considered
NA

## Additional context
NA

## Ownership of Contribution
If the triage is approved,
- [ ] I wish to submit the PR myself.
- [x] I wish to submit the PR. But if someone is willing to do it, go ahead.
- [ ] I don't know how to fix this or make these changes. I wish others to pick this up for me.
